### ISSUE TITLE
Dimcli build failed with Visual Studio 2019 due to warning C5055

### ISSUE THREAD

**Issue by LilyWangL** [gknowles/dimcli#15]
**Description:**
Dimcli 5.0.0 build failed with Visual Studio 2019 due to warning C5055.

**Failures:**
5>F:\0814\vcpkg\buildtrees\dimcli\src\v5.0.0-89211a3afb\libs\dimcli\cli.h(1501,15): error C2220:  warning treated as error - no 'object' file generated [F:\0814\vcpkg\buildtrees\dimcli\x64-windows-dbg\cli.vcxproj]
5>F:\0814\vcpkg\buildtrees\dimcli\src\v5.0.0-89211a3afb\libs\dimcli\cli.h(1501,15): warning C5055:  operator '>=': deprecated between enumerations and floating-point types 

Attach my build log:
[install-x64-windows-dbg-out.log](https://github.com/gknowles/dimcli/files/3540530/install-x64-windows-dbg-out.log)

**Comment by gknowles** [comment]
Thanks for your interest and the report!

That was moved down one line and should've been fixed by https://github.com/gknowles/dimcli/commit/e884bc4bb7fa3de82b7d856967a62c834c5c16c1 on 2019-08-14 (and then fixed for clang the next day :P).

It's building for me with 2019 16.2.3 and the appveyor build using a slightly older 2019.

Please pull the latest, try again, and let me know if it still failing.

**Comment by gknowles** [comment]
Thinking about it, this seemed worth a patch release. 

The new 5.0.1 release includes this fix.

**Comment by LilyWangL** [comment]
Thanks for your support! I installed it successfully.
